import Head from "next/head";
import type { ReactNode } from "react";

type LayoutProps = {
  children: ReactNode;
  Alerts: JSX.Element | null;
};

export const Layout = ({ children, Alerts = null }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>SB Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      {Alerts}
    </>
  );
};
